server:
  port: 8000

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level){bright}%clr([%thread]) %clr(%logger{36}){cyan}:%line - %clr(%msg){magenta}%n"
  level:
    com.epam: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchdb?createDatabaseIfNotExist=true
    username: root
    password: Danvi@02
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false

sonar:
  projectKey: rd
  projectName: rd
  host:
    url: http://localhost:9000
  login: admin
  password: DanviShanmuki@2